Vagrant.configure(2) do |config|
  config.vm.box = "scotch/box"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network",
                    use_dhcp_assigned_default_route: true
  
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../data", "/vagrant_data"

  # Disable VirtualBox DNS proxy as it may cause issues.
  # See https://github.com/docker/machine/pull/1069
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
  end
  config.vm.provision "shell", inline: $shell
end


$shell = <<-SHELL
PROVISIONED=/usr/local/etc/vagrant_provisioned

        if [-f ${PROVISIONED} ]; then
                exit 0
        fi
        echo "Provisioning..."
        sudo apt-get update
        sudo apt-get install -y build-essential wget git emacs
        sudo apt-get install -y bzip2 unzip p7zip-full
        sudo apt-get install -y openssl htop
        if [ ! -d ~vagrant/repos ]; then
            git clone https://github.com/sdaaish/dotfiles.git ~vagrant/repos/dotfiles
        fi
        touch ${PROVISIONED}
SHELL
